({
  loadStateOptions: function(component, event, helper) {
    var opts = [
      { "value": "AL", "label": "AL", "selected": false },
      { "value": "AK", "label": "AK", "selected": false },
      { "value": "AZ", "label": "AZ", "selected": false },
      { "value": "AR", "label": "AR", "selected": false },
      { "value": "CA", "label": "CA", "selected": false },
      { "value": "CO", "label": "CO", "selected": false },
      { "value": "CT", "label": "CT", "selected": false },
      { "value": "DE", "label": "DE", "selected": false },
      { "value": "DC", "label": "DC", "selected": false },
      { "value": "FL", "label": "FL", "selected": false },
      { "value": "GA", "label": "GA", "selected": false },
      { "value": "HI", "label": "HI", "selected": false },
      { "value": "ID", "label": "ID", "selected": false },
      { "value": "IL", "label": "IL", "selected": false },
      { "value": "IN", "label": "IN", "selected": false },
      { "value": "IA", "label": "IA", "selected": false },
      { "value": "KS", "label": "KS", "selected": false },
      { "value": "KY", "label": "KY", "selected": false },
      { "value": "LA", "label": "LA", "selected": false },
      { "value": "ME", "label": "ME", "selected": false },
      { "value": "MD", "label": "MD", "selected": false },
      { "value": "MA", "label": "MA", "selected": false },
      { "value": "MI", "label": "MI", "selected": false },
      { "value": "MN", "label": "MN", "selected": false },
      { "value": "MS", "label": "MS", "selected": false },
      { "value": "MO", "label": "MO", "selected": false },
      { "value": "MT", "label": "MT", "selected": false },
      { "value": "NE", "label": "NE", "selected": false },
      { "value": "NV", "label": "NV", "selected": false },
      { "value": "NH", "label": "NH", "selected": false },
      { "value": "NJ", "label": "NJ", "selected": false },
      { "value": "NM", "label": "NM", "selected": false },
      { "value": "NY", "label": "NY", "selected": false },
      { "value": "NC", "label": "NC", "selected": false },
      { "value": "ND", "label": "ND", "selected": false },
      { "value": "OH", "label": "OH", "selected": false },
      { "value": "OK", "label": "OK", "selected": false },
      { "value": "OR", "label": "OR", "selected": false },
      { "value": "PA", "label": "PA", "selected": false },
      { "value": "RI", "label": "RI", "selected": false },
      { "value": "SC", "label": "SC", "selected": false },
      { "value": "SD", "label": "SD", "selected": false },
      { "value": "TN", "label": "TN", "selected": false },
      { "value": "TX", "label": "TX", "selected": false },
      { "value": "UT", "label": "UT", "selected": false },
      { "value": "VT", "label": "VT", "selected": false },
      { "value": "VA", "label": "VA", "selected": false },
      { "value": "WA", "label": "WA", "selected": false },
      { "value": "WV", "label": "WV", "selected": false },
      { "value": "WI", "label": "WI", "selected": false },
      { "value": "WY", "label": "WY", "selected": false }
        ];
    component.set("v.stateOptions", opts);
  },
})
